proposal/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns("proposal.views",
                       url('^create/$', 'create_proposal', name='create'),
                       url('^list/$', 'list_proposal', name='list'),
                       url('^update/(\d+)/$', 'update_proposal', name='update'),
                       url('^upload_abstract/(\d+)/$', 'upload_abstract', name='upload_abstract'),
                       url('^delete/(\d+)/$', 'delete_proposal', name='delete'),
                       )

proposal/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class ProposalModel(models.Model):

    LANGUAGE_CHOICES = (
        (0, _("English")),
        (1, _("Mandarin")),
    )

    SPEECH_TYPE_CHOICES = (
        (0, _("Regular Talk")),
        (1, _("Lightning Talk")),
        (2, _("SciPy Talk")),
        (3, _("Tutorial")),
    )

    LEVEL_CHOICES = (
        (0, _("Beginner")),
        (1, _("Advanced")),
        (2, _("Expert")),
        (3, _("Scientific Background")),
    )

    TALK_PERMISSION_CHOICES = (
        (1, _("CC-BY-NC-SA")),
        (0, _("Don't record my talk")),
    )

    SLIDE_PERMISSION_CHOICES = (
        (1, _("CC-BY-NC-SA")),
        (0, _("Don't publish my slide")),
    )

    title = models.CharField(verbose_name=_("Title"),
                             help_text=_("Title of the talk or tutorial"),
                             max_length=100)
    author = models.ForeignKey("auth.User")
    speech_type = models.IntegerField(verbose_name=_("Type of the proposal"),
                                      choices=SPEECH_TYPE_CHOICES)
    language = models.IntegerField(
        verbose_name=_("Language"),
        choices=LANGUAGE_CHOICES,
        help_text=_("SciPy Talk accepts only English")
    )
    audience_level = models.IntegerField(verbose_name=_("Audience level"),
                                         choices=LEVEL_CHOICES)
    talk_perm = models.IntegerField(
        choices=TALK_PERMISSION_CHOICES,
        verbose_name=_(
            "Permission for your talk to be recorded "
            "and released on the conference website"),
    )
    slide_perm = models.IntegerField(
        choices=SLIDE_PERMISSION_CHOICES, null=True, blank=True,
        verbose_name=_(
            "Permission for your presentation slide to"
            " be downloaded from the conference website"),
    )
    description = models.TextField(
        verbose_name=_("Description"),
        help_text=_("Abstract or outline of your presentation. ")
    )
    additional_info = models.TextField(
        verbose_name=_("Additional information"), null=True, blank=True,
        help_text=_("Additional information that can help the program"
                    " committee to make decisions (e.g., years of experie)")
    )
    create_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)


class AbstractFile(models.Model):
    proposal = models.OneToOneField(ProposalModel)
    abstract = models.FileField(verbose_name=_("Abstract"),
                                upload_to="abstract", null=True, blank=True)

    @property
    def has_file(self):
        return bool(self.abstract)

    def url(self):
        # Shortcuts of file url.
        return self.abstract.url if self.has_file else ""

    def __unicode__(self):
        return self.abstract.name.split('/')[-1] if self.has_file else ""

proposal/forms.py
from os.path import splitext

from django import forms
from django.utils.translation import ugettext as _
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import UploadedFile

from .models import ProposalModel, AbstractFile


class ProposalForm(forms.ModelForm):

    class Meta:
        model = ProposalModel
        exclude = ("create_on", "last_modified", "author", "slide_perm")


class AbstractFileForm(forms.ModelForm):

    class Meta:
        model = AbstractFile
        fields = ("abstract",)

    def clean_abstract(self):
        abstract_file = self.cleaned_data.get('abstract')
        if abstract_file:
            # If it is a newly file, it will be an instance of "UploadedFile".
            if isinstance(abstract_file, UploadedFile):
                # Check its file format.
                discarded, file_extension = splitext(abstract_file.name)
                if file_extension != ".pdf":
                    raise ValidationError(_("File format should be PDF."))
            return abstract_file
        else:
            raise ValidationError(_("Upload Failure."))

proposal/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseNotAllowed, HttpResponseForbidden
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.core.exceptions import PermissionDenied

from .forms import ProposalForm, AbstractFileForm
from .models import ProposalModel, AbstractFile


@login_required
def create_proposal(request):

    if not settings.CALL_FOR_PROPOSAL:
        raise PermissionDenied("Time is up.")

    if request.method == "POST":

        proposal_form = ProposalForm(request.POST, request.FILES)

        if proposal_form.is_valid():
            proposal = proposal_form.save(commit=False)
            proposal.author = request.user
            proposal.save()
            message = _("Thanks for your submission!")
            messages.add_message(request, messages.SUCCESS, message)
            return redirect(reverse("proposal:list"))
        else:
            return render(request, "proposal/create.html",
                          {"proposal_form": proposal_form})
    else:

        proposal_form = ProposalForm()

        return render(request, "proposal/create.html",
                      {"proposal_form": proposal_form})


@login_required
def list_proposal(request):

    my_proposal = ProposalModel.objects.filter(author=request.user)
    return render(request, "proposal/list.html",
                  {"my_proposal": my_proposal,
                   "upload_abstract_form": AbstractFileForm})


@login_required
def update_proposal(request, proposal_id):

    proposal = ProposalModel.objects.get(id=proposal_id, author=request.user)

    if not proposal:
        return HttpResponseForbidden("Permission Denied.")

    if request.method == "POST":
        proposal_form = ProposalForm(request.POST, request.FILES,
                                     instance=proposal)
        if proposal_form.is_valid():
            proposal_form.save()
            message = _("Proposal updated")
            messages.add_message(request, messages.SUCCESS, message)
            return redirect(reverse("proposal:list"))
        else:
            return render(request, "proposal/create.html",
                          {"proposal_form": proposal_form})
    else:
        proposal_form = ProposalForm(instance=proposal)
        return render(request, "proposal/create.html",
                      {"proposal_form": proposal_form})


@login_required
def delete_proposal(request, proposal_id):

    if not settings.CALL_FOR_PROPOSAL:
        raise PermissionDenied("Time is up.")

    proposal = ProposalModel.objects.get(id=proposal_id, author=request.user)

    if not proposal:
        return HttpResponseForbidden("Permission Denied.")

    if request.method == "POST":
        proposal.delete()
        return redirect(reverse("proposal:list"))

    else:
        return HttpResponseNotAllowed("")


@login_required
def upload_abstract(request, proposal_id):

    if request.method == "POST":

        abstract_file, success = \
            AbstractFile.objects.get_or_create(proposal_id=proposal_id)

        abstract_file_form = AbstractFileForm(request.POST, request.FILES,
                                              instance=abstract_file)

        if abstract_file_form.is_valid():
            abstract_file_form.save()
        else:
            for field, message in abstract_file_form.errors.items():
                messages.add_message(request, messages.ERROR, message)

        return redirect(reverse("proposal:list"))
    else:
        return HttpResponseNotAllowed("")

proposal/templates/proposal/create.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap3 %}

{% block meta_title_block %}PyCon APAC 2014{% endblock %}

{% block title %}{% trans "Create Proposal" %}{% endblock %}

{% block .breadcrumb %}{% endblock %}

{% block content %}
  <div class="content">
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-12">
        <br>
        <p>
          {% blocktrans %}
          PyCon APAC 2014 is now accepting all types of proposals.
          {% endblocktrans %}
        </p>
        <hr>

      </div>
      <div class="col-md-7">
      <form class="form" method="post" action="." enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form proposal_form %}
          {% buttons %}
              <hr>
              <button type="submit" class="btn btn-primary btn-lg">
                  {% bootstrap_icon "star" %} {% trans "Submit" %}
              </button>
          {% endbuttons %}
      </form>
      </div>
      <div class="col-md-5">
        {% blocktrans %}
        <div class="well note">
          <h4>Note</h4>
          <ul class="square-list">
            <li>
              You can submit your abstract in PDF after filling this form.
            </li>
            <li>
              For SciPy Talk, an extended abstract of 1 to 3 A4 pages is required.
            </li>
          </ul>

        </div>
        {% endblocktrans %}
        {% blocktrans %}
        <div class="well note">

          <h4>Important Dates</h4>
          <ul class="square-list">
            <li>
            <span>Dec 15, 2013</span> <br> Opening of Call for Proposals
            </li>
            <li>
            <big>Mar 10, 2014</big> <br> Deadline for Proposal Submissions
            </li>
            <li>
            <big>Mar 24, 2014</big> <br> Notification of Proposal Acceptance
            </li>
            <li>
            May 16, 2014 <br> Tutorial Day
            </li>
            <li>
            May 17 - 18, 2014 <br> PyCon APAC Conference Days
            </li>
          </ul>
        </div>
        {% endblocktrans %}
      </div>
      <div class="clearfix">
      </div>
    </div>

  </div>


{% endblock %}

proposal/templates/proposal/list.html
{% extends "base.html" %}
{% load i18n %}

{% block meta_title_block %}PyCon APAC 2014{% endblock %}

{% block extra_head %}
<script>
    $(function(){
        $(".btn.delete-proposal").on("click", function(event){
            var $target = $(event.target);
            var action = $target.attr("data-href");
            var $modal = $("#proposal-delete-modal");
            $modal.find("form").attr("action", action);
            $modal.modal({
                "backdrop": "static",
                "show": true
            });
        });

        $(".btn.upload-abstract").on("click", function(event){
            var $target = $(event.target);
            var action = $target.attr("data-href");
            var $modal = $("#upload-abstract-modal");
            $modal.find("form").attr("action", action);
            $modal.modal({
                "backdrop": "static",
                "show": true
            });
        });
    });
</script>
{% endblock %}


{% block title %}{% trans "My Proposals" %}{% endblock %}

{% block .breadcrumb %}{% endblock %}

{% block content %}


<div class="content">
    <p class="action-btn-block">
        {% if CALL_FOR_PROPOSAL %}
        <a class="btn btn-default btn-lg" href="{% url "proposal:create" %}">{% trans "Create a Proposal" %}</a>
        {% endif %}
    </p>

    {% for proposal in my_proposal %}


      <div class="paper">
        <h3 class="d-title">
          {{proposal.title}}
          <small>by</small>
          {{proposal.author.get_full_name}}
        </h3>
        <hr>
        <div class="row">
          <div class="col-md-4">
            <dl class="dl-info">
              <dt>{% trans "Speech Type" %}</dt>
              <dd>{{proposal.get_speech_type_display}}</dd>
              <dt>{% trans "Audience level" %}</dt>
              <dd>{{proposal.get_audience_level_display}}</dd>
            </dl>
          </div>
          <div class="col-md-4">
            <dl class="dl-info">
              <dt>{% trans "Language" %}</dt>
              <dd>{{proposal.get_language_display}}</dd>
              <dt>{% trans "Recording Perm." %}</dt>
              <dd>{{proposal.get_talk_perm_display}}</dd>
            </dl>
          </div>
          <div class="col-md-4">
            <dl class="dl-info">
              <dt>{% trans "Abstract" %} <span class="note">{% trans "(PDF file)" %}</span></dt>
              <dd>
                {% if proposal.abstractfile and proposal.abstractfile.has_file %}
                <a href="{{proposal.abstractfile.url}}" target="_blank">
                {{proposal.abstractfile}}
                </a>
                {% else %}
                <span>{% trans "No abstract file." %}</span>
                {% endif %}
                &nbsp;
                <button data-href="{% url "proposal:upload_abstract" proposal.id %}" class="btn btn-info upload-abstract">{% trans "Upload" %}</button>

              </dd>
            </dl>
          </div>
        </div>
        <div class="clear"></div>
        <hr>
        <div class="row">
          <div class="col-md-9">
            <dl class="dl-info">
              <dt>{% trans "Description" %}</dt>
              <dd><pre>{{proposal.description}}</pre></dd>
              <dt>{% trans "Additional information" %}</dt>
              <dd><pre>{{proposal.additional_info}}</pre></dd>
            </dl>
            <hr>
            <p class="text-right">
              <a href="{% url "proposal:update" proposal.id %}" class="btn btn-info">{% trans "Update" %}</a>
              {% if CALL_FOR_PROPOSAL %}
              <button data-href="{% url "proposal:delete" proposal.id %}" class="btn btn-danger delete-proposal">{% trans "Delete" %}</button>
              {% endif %}
            </p>
          </div>
        </div>


      </div>

    {% empty %}
      <hr>
      <p>{% trans "No Proposal" %}</p>
    {% endfor %}

</div>


<div id="upload-abstract-modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4>{% trans "Upload Abstract" %}</h4>
            </div>
            <form class="form-inline" method="post" action="." enctype="multipart/form-data">
            <div class="modal-body">
                {% csrf_token %}
                {{ upload_abstract_form.as_p }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                <button type="submit" class="btn btn-danger">{% trans "Upload" %}</button>
            </div>
            </form>
        </div>
    </div>
</div>

<div id="proposal-delete-modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4>{% trans "Delete Proposal" %}</h4>
            </div>
            <div class="modal-body">
              {% blocktrans %}
                Are you sure to <strong>delete</strong> this proposal?
              {% endblocktrans %}
            </div>
            <div class="modal-footer">
                <form class="form-inline" method="post" action=".">
                    {% csrf_token %}
                    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                    <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block sider %}{% endblock %}